### ISSUE TITLE
mutate-arc utility puts new item on the end of the previous line

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#115]
If you add this test to the cli `mutate-arc.test.js` unit test:
```javascript
test('Item followed by map', t => {
  t.plan(1)
  let before = `@app
begin-app

@plugins
enhance/arc-plugin-enhance
`

  const after = `@app
begin-app

@plugins
enhance/arc-plugin-enhance
authentication
  src plugins/authentication
`

  let item = 'authentication\n  src plugins/authentication'
  let pragma = 'plugins'
  let result = mutateArc.upsert({ item, pragma, raw: before })
  t.equal(result, after, 'Mutated arc file wite map items')
})
```
You get the following:
<img width="565" alt="Screen Shot 2022-11-21 at 11 31 10 AM" src="https://user-images.githubusercontent.com/26754584/203108558-7af2bf2a-930c-402b-a395-78fc88c1bd81.png">
The resulting item ends up appended to the previous item. If you add a new line at the beginning of the item it works, but it adds an extra empty line before the item.

**Comment by ryanblock** [comment]
Thanks, I can see where the bug is – this is isolated to insertions after string values, which in the AST do not contain their own trailing newlines, unlike complex types (maps, arrays, vectors). Stand by!
