### ISSUE TITLE
Make it easier to get your access token from the CLI

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#120]
You need to set your begin access token in GitHub secrets to be able to deploy via an action. It would be great if `begin login` would copy your access token to the clipboard or `begin login --json` would include it as part of it's output.

**Comment by tbeseda** [comment]
Hey @macdonst does the `begin tokens list` command help?

```
> begin tokens list --display
Client tokens
└──  < R E D A C T E D >
    ├── created:   2024-01-10T21:31:02.275Z
    ├── last used: 2024-01-23T19:14:55.291Z
    └── expires:   2024-03-23T19:14:55.000Z
```

using the `--display` flag will print the token in full (mine is `< R E D A C T E D >`)

**Comment by macdonst** [comment]
@tbeseda works for me. Pretty sure the `tokens` command didn't exist when I opened the issue.
