### ISSUE TITLE
Using `Pages` as a model name in the CRUD scaffolder causes a syntax error in the generated code

### ISSUE THREAD

**Issue by knowler** [beginner-corp/cli#136]
If you make the model name `Pages` for `begin generate scaffold` this particular bit will cause a syntax error since it will declare two variables called `pages` in this function:

https://github.com/beginner-corp/cli/blob/68b10e36c97a0ecbefda753d4e199a0d5c3cbd5d/src/commands/generate/generators/scaffold/handlers/model.js#L19-L34

**Comment by macdonst** [comment]
Will be fixed in 0.12.1
