### ISSUE TITLE
Sort regions list

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#150]
When you are selecting a region from the list of available regions, they are not sorted by any order that is obvious to users.

```
? Select from these regions …
  N. California, US
  Oregon, US
  N. Virginia, US
  Ohio, US
  Montréal, CA
  Tokyo, JP
  Seoul, KR
  Mumbai, IN
  Singapore, SG
  Sydney, AU
  Frankfurt, DE
  Stockholm, SE
  Dublin, IE
  London, GB
  Paris, FR
  São Paulo, BR
```

We should probably sort it alphabetically.

**Comment by tbeseda** [comment]
Right now it's sorted by global region, which makes most sense to me.

```
us-
us-
us-
us-
ca-
ap-
ap-
ap-
ap-
ap-
eu-
eu-
eu-
eu-
eu-
sa-
```

I don't think sorting alphabetically is helpful here unless you know what string you're looking for.

```
  Dublin, IE
  Frankfurt, DE
  London, GB
  Montréal, CA
  Mumbai, IN
  N. California, US
  N. Virginia, US
  Ohio, US
  Oregon, US
  Paris, FR
  São Paulo, BR
  Seoul, KR
  Singapore, SG
  Stockholm, SE
  Sydney, AU
  Tokyo, JP
```

This mixes US (the only country with multiple regions) across the list.

Say I live in Denver, I'd scan the top for "Denver", realize it's not there, then look for recognizable cities nearby, realize this is an international list, scan for the US country code at the end of each line, do the mental geography math for each "US" region, and eventually pick one.

If I live in Toronto: assuming I realize it's alphabetical, scan to end for "T", no dice, look for "CA" (and hope it doesn't mean "California" 🫠), find Montreal, settle on Ohio maybe.

My point is it's a crapshoot. If we did want better sort criteria, we'd probably adjust in the API at /apps/regions. Like, which region is closest to the current user's current IP address? could be cool

Perhaps the best option is to go ahead and include the region identifier from AWS?

**Comment by tbeseda** [comment]
> Perhaps the best option is to go ahead and include the region identifier from AWS?

oh this is what Brian suggests https://github.com/beginner-corp/cli/issues/149

Closing this since #149 was technically first and doesn't have my wall of text 🙃
