### ISSUE TITLE
Creating an environment called `testing` fails

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#165]
I was attempting to create a new environment called `testing`. The command failed and I got a message that said the `staging` environment already exists.

## Expected behaviour

The `testing` environment gets created since this would be a very common environment name. Alternatively, a better explanation of why `testing` === `staging` to the CLI.

## Steps to reproduce

1. Create an app with `begin create` naming your first environment `staging`
2. Attempt to create a new environment called `testing`

```bash
begin create -e testing
Error: Environment name cannot be 'staging'
```

## Platform version

- MacOS 14.2.1
- Begin version: main-21f0079
- Node.js v18.15.0

**Comment by tbeseda** [comment]
This line here is preventing app env creation with the name "staging"

```js
    if (name === 'testing') throw ReferenceError(cannotBeStaging)
```

https://github.com/beginner-corp/cli/blob/a7cefee9472c82f60a14e206aae078b4aa21980c/src/lib/app/validate.js#L8

I'm unsure if it should be `if name == 'staging'` bc I'm also unsure what the reasoning is.

I can adjust as needed, just need clarification. Thanks

**Comment by tbeseda** [comment]
Another follow up: the "testing" env name should be disallowed as it can lead to real confusion and conflicts when running a testing environment locally.
So I've changed the variable name and improved the error message
