### ISSUE TITLE
running begin login on linux, 403 status code error  is returned.

### ISSUE THREAD

**Issue by silaselisha** [beginner-corp/cli#184]
For context, I followed the installation guide provided at https://begin.com/deploy/docs/getting-started/installing-the-begin-cli
but when trying to run `begin login` I get  `Error: POST failed with: 403`

**Comment by digitalicarus** [comment]
I experienced the same issue attempting to follow the quickstart. I'm running on an Arch Linux guest inside Virtualbox and haven't had any other networking or access issues whatsoever. I'm also using nvm on node version 20.14.0. Screenshots of console command with debug flag and command history attached.
![image](https://github.com/beginner-corp/cli/assets/662374/58ea22be-ec91-41fe-9b12-54a0f2546f0f)
![image](https://github.com/beginner-corp/cli/assets/662374/a7ab2dca-620e-4cf0-a611-8a2c26f16f8f)
![image](https://github.com/beginner-corp/cli/assets/662374/88175940-bb81-4414-8fe3-ae22a507ad3b)

**Comment by silaselisha** [comment]
@digitalicarus I would like to know if you are interested in collaborating with me to find a solution

**Comment by tbeseda** [comment]
@silaselisha @digitalicarus thanks for reporting and apologies the original issue went unhandled for so long. I will take a look. This information is helpful!

**Comment by tbeseda** [comment]
I've got a fix publishing to npm right now. It was a bug I introduced a while back and wasn't Linux specific; just so happens you two found it.

If you could try with the recent patch `0.22.5` and validate that you're able to login, that would be very helpful.

**Comment by silaselisha** [comment]
@tbeseda Thank you for the fix. It works well now.
