### ISSUE TITLE
Pluralize can give us the same name for singular and plural

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#36]
For instance, try Moose.

**Comment by ryanblock** [comment]
Is this issue still valid?

**Comment by macdonst** [comment]
Yes, this is still a valid issue.

**Comment by ryanblock** [comment]
Ok, I'm not really sure what to do with this issue, can it be expanded so other folks can take a look at it?

**Comment by macdonst** [comment]
@ryanblock it's not critical. It's more of a reminder for myself to get back to it someday. For now I think we are okay as long as no one runs `begin generate scaffold Moose`

**Comment by macdonst** [comment]
Closed in favour of https://github.com/enhance-dev/cli/issues/9
