### ISSUE TITLE
`begin dev` doesn't run sandbox startup scripts

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#46]
Possibly a path error

**Comment by macdonst** [comment]
@ryanbethel I think I figured out why you are running into this problem. A generated project skips adding aws-sdk as a dependency as it is always available in the lambda. It expects the local dev environment to have it installed globally. The other then the `generate scaffold` command does is call the method `installAwsSdk()`. This checks to see if the environment has a version of the sdk installed and if not it installs it as a dev dep.

**Comment by ryanbethel** [comment]
This seems to be related to startup scripts and esm. The startup script uses `@begin/data` to seed the database. If the script is written as a .mjs file with `import` it will run with `npm start` but fails silently with `begin dev`. If it is changed to a .js file with require it will run with `begin dev`.  For @macdonst the same happens with the `@bundles`. If fails for begin dev and runs with npm start.
