### ISSUE TITLE
PLACEHOLDER issue: installing sandbox dependency tree

### ISSUE THREAD

**Issue by tbeseda** [beginner-corp/cli#57]
[I was unsure where to file this, so I'm leaving it here for now since the CLI is where it surfaces]

I think `leveldown` runs node-gyp meta stuff.

Begin's deploy logs say:

```
sh: node-gyp-build: command not found
```

leveldown belongs to dynalite

```
npm ls leveldown

enhance-alpine@ /Users/tbeseda/dev/scratch/enhance-alpine
└─┬ @architect/sandbox@5.3.4
  └─┬ dynalite@3.2.2
    └── leveldown@5.6.0
```

**Comment by ryanblock** [comment]
Not sure what this issue is, are there repro steps?
