### ISSUE TITLE
Begin deploy fails with dep using relative `file:../../../` reference

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#71]
If a dependency uses a relative reference like: 
```json
 "dependencies": {
    "@enhance/arc-plugin-enhance": "file:../../../src/plugin/"
  },
```
It will run in `begin dev` or `arc sandbox` but it will fail to deploy with `begin deploy` with the following error:
```
Error: Begin exception: Plugin error:
- Cannot find plugin 'enhance/arc-plugin-enhance'! Are you sure you have installed or created it correctly?
```

I usually only need to do this if I am testing a plugin from a directory inside that repository. 

Here is a repository that reporduces the error. I install the starter app with `begin new project`, then move the plugin to a directory outside that project directory, and reference it relatively.
[repro-repo](https://github.com/ryanbethel/tmp-rel-path-pkg.git)

**Comment by ryanbethel** [comment]
I can use a different approach for testing. I understand that this is an unsupported use case. A project should have all dependencies inside the project folder.

**Comment by ryanblock** [comment]
OK, I see what's going on here now. Begin deploys from the project directory; it takes all of the contents of that project directory and sends it to the deployment API to publish. It is not inspecting the paths of any of the project's dependencies or the require or import statements in its business logic, it expects that if something is specified in the project, it would be found somewhere within the project folder. So this is not something that is going to work.
