### ISSUE TITLE
Deploy strips quotes in arc file

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#72]
If you have quotes in the arc file:
```
@bundles
store 'node_modules/@enhance/store'
parser 'node_modules/@architect/parser'
```
and you deploy the CLI will strip the quotes off and the arc file will fail because of the @ symbol inside the string.

**Comment by macdonst** [comment]
- Fixed @architect/parser
- Updated dependency in CLI
- Added test case
