### ISSUE TITLE
Set Begin AppID with CLI argument for CI

### ISSUE THREAD

**Issue by ryanbethel** [beginner-corp/cli#76]
It would be nice to be able to set the begin appID with a command line argument that does not get added to the .arc file. This would be useful for CI and integration testing where the appID could be specified in Github secrets etc.

**Comment by ryanblock** [comment]
Hmm, Which workflows? More info pls!

**Comment by ryanbethel** [comment]
For instance I wanted to add a staging test to a repo for a feature that cannot be tested in sandbox (i.e. accessing fingerprinted files). To do that I might run `begin deploy` in Github actions to deploy to a staging app and run tests against that. It would make the most sense to store the app id for that in github secrets and pass it as a command line argument than to have it in the repo in the .arc file. I could also write it to the .arc file in GA before running begin deploy. This is more of a feature suggestion.

**Comment by ryanblock** [comment]
This can be done for stateless workflows, such as: `builds`, `create`, `destroy`, `env`, `logs`, and we should definitely do that. `deploy` is a stateful workload, however, and must be run contextually within a project directory containing an app ID.
